version: "3.9"

services:
  web:
    command: >
      sh -c "poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:${PORT}"
    container_name: korablinbot
    depends_on:
      - redis
      - celery
    env_file:
      - dev.env
    image: korablinbot:dev
    ports:
      - 8000:8000

  celery:
    build: .
    command: poetry run celery -A app worker -l INFO
    container_name: celery
    depends_on:
      - redis
    env_file:
      - dev.env
    image: korablinbot:dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379