version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "poetry run python setup_webhook.py &&
             poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py migrate &&
             poetry run gunicorn --workers=1 --bind=0.0.0.0:${PORT} app.wsgi"
    container_name: korablinbot
    depends_on:
      - redis
      - celery
    env_file:
      - .env
#    image: korablinbot:latest
    ports:
      - 8000:8000

  celery:
    build: .
    command: poetry run celery -A app worker -l INFO
    container_name: celery
    depends_on:
      - redis
    env_file:
      - .env
#    image: korablinbot:latest

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379